import "./globals.css";
import { AppContextProvider } from "@/context/AppContext";
import { AuthContextProvider } from "@/context/AuthContext";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Ai-Survey",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className='h-dvh w-full relative bg-white'
      >
        <AppContextProvider>
          <AuthContextProvider>
            <Toaster position="top-center" />
            {children}
          </AuthContextProvider>
        </AppContextProvider>
      </body>
    </html>
  );
}
